# Generated by Django 4.2.1 on 2023-05-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('P', 'Paga'), ('A', 'Atrasada'), ('E', 'Pendente')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('descrição', models.CharField(max_length=30)),
                ('quantidade', models.FloatField()),
                ('valor_pagamento', models.FloatField()),
                ('valor_recebimento', models.FloatField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.categoria')),
            ],
        ),
    ]
